options:
  config-file: 'node_modules/sass-lint-config-brainly/.sass-lint.yml'
rules:
  # Enforce that mixins should be written before declarations in a ruleset.
  mixins-before-declarations:
    - 2
    - exclude: ['sgBreakpoint', 'sgResponsive']
  variable-name-format:
    - 2
    - allow-leading-underscore: true
      convention: ^(([a-z][a-zA-Z0-9]+)+|[a-z\-0-9]+)$
      convention-explanation: 'Variable must be either camelcase or hyphenatedlowercase'
