scss_files: 'src/**/*.scss'
exclude: ['src/sass/vendors/**', 'src/docs/css/**', 'src/components/icons/_icons-data.scss']

linters:
  # Only 1 BEM element in selector allowed
  # Good: .block__element
  # Bad: .block__element__subelement
  BemDepth:
    enabled: true
    max_elements: 1
  # Prefer the terser "border: none" over "border: 0".
  BorderZero:
    convention: none
  # Prefer hexadecimal color codes over color keywords.
  ColorKeyword:
    enabled: true
  # Prefer color literals to be used only in variable declarations.
  ColorVariable:
    enabled: true
  # Disabled - Prefer // comments over /* ... */.
  Comment:
    enabled: false
  # Reports @debug statements (which you probably left behind accidentally).
  DebugStatement:
    enabled: true
  # Rule sets should be ordered as follows:
  # @extend declarations, @include declarations without inner @content, properties,
  # @include declarations with inner @content, then nested rule sets.
  DeclarationOrder:
    enabled: true
  # Reports when you define the same property twice in a single rule set.
  DuplicateProperty:
    enabled: true
  # Place @else statements on the same line as the preceding curly brace.
  ElsePlacement:
    enabled: true
  # Separate rule, function, and mixin declarations with empty lines.
  EmptyLineBetweenBlocks:
    enabled: true
  # Reports when you have an empty rule set.
  EmptyRule:
    enabled: true
  # Files should always have a final newline.
  FinalNewline:
    enabled: true
  # You can specify whether you prefer shorthand or long-form hexadecimal colors
  # by setting the style option to short or long, respectively.
  HexLength:
    style: long
  # Checks if hexadecimal colors are written in lowercase/uppercase.
  HexNotation:
    style: lowercase
  # Ensure hexadecimal colors are valid
  HexValidation:
    enabled: true
  # Avoid using ID selectors.
  IdSelector:
    enabled: true
  # Avoid using !important in properties.
  ImportantRule:
    enabled: true
  # The basenames of @imported SCSS partials should not begin with an underscore
  # and should not include the filename extension.
  ImportPath:
    enabled: true
  # Use two spaces per indentation level.
  Indentation:
    character: space
    width: 2
  # Write leading zeros for numeric values with a decimal point like 0.5em
  LeadingZero:
    style: include_zero
  # Reports when you define the same selector twice in a single sheet.
  MergeableSelector:
    enabled: true
  # Functions, mixins, variables, and placeholders name formats
  NameFormat:
    allow_leading_underscore: true # Allow names to start with a single underscore
    convention: camel_case
  # Avoid nesting selectors too deeply.
  NestingDepth:
    max_depth: 3
  # Always use placeholder selectors in @extend
  PlaceholderInExtend:
    enabled: true
  # Limit the number of properties in a rule set.
  PropertyCount:
    enabled: true
    max_properties: 12
  # Sort properties in a strict order.
  PropertySortOrder:
    enabled: false
  # Reports when you use an unknown CSS property
  PropertySpelling:
    enabled: true
  # Avoid qualifying elements in selectors (like ul.list ).
  QualifyingElement:
    enabled: true
  # Don't write selectors with a depth of applicability greater than 3.
  SelectorDepth:
    max_depth: 3
  # Convention for naming selectors.
  SelectorFormat:
    convention: hyphenated_BEM
  # Prefer the shortest shorthand form possible for properties that support it.
  Shorthand:
    enabled: true
  # Properties within rule sets should each reside on their own line.
  SingleLinePerProperty:
   enabled: true
  # Split selectors onto separate lines after each comma,
  # and have each individual selector occupy a single line.
  SingleLinePerSelector:
    enabled: true
  # Commas in lists should be followed by a space.
  SpaceAfterComma:
    enabled: true
  # Properties should be formatted with a single space separating the colon from the property's value.
  SpaceAfterPropertyColon:
    enabled: true
  # Properties should be formatted with no space between the name and the colon.
  SpaceAfterPropertyName:
    enable: true
  # Variables should be formatted with no space between the name and the colon.
  SpaceAfterVariableName:
    enabled: true
  # Operators should be formatted with a single space on both sides of an infix operator.
  SpaceAroundOperator:
    enabled: true
  # Opening braces should be preceded by a single space.
  SpaceBeforeBrace:
    enabled: true
  # Parentheses should not be padded with spaces.
  SpaceBetweenParens:
    enabled: true
  # String literals should be written with single quotes
  StringQuotes:
    enabled: true
  # Property values; @extend, @include, and @import directives;
  # and variable declarations should always end with a semicolon.
  TrailingSemicolon:
    enabled: true
  # Reports lines containing trailing whitespace.
  TrailingWhitespace:
    enabled: true
  # Don't write trailing zeros for numeric values with a decimal point.
  TrailingZero:
    enabled: true
  # Don't use the all keyword to specify transition properties.
  TransitionAll:
    enabled: true
  # Numeric values should not contain unnecessary fractional portions.
  UnnecessaryMantissa:
    enabled: true
  # Do not use parent selector references (&) when they would otherwise be unnecessary.
  UnnecessaryParentReference:
    enable: true
  # URLs should not contain protocols or domain names.
  UrlFormat:
    enabled: true
  # URLs should always be enclosed within quotes.
  UrlQuotes:
    enabled: true
  # Properties, like color and font, are easier to read and maintain
  # when defined using variables rather than literals.
  VariableForProperty:
    enabled: true
    properties:
      - color
      - font
      - font-size
      - font-family
  # Avoid vendor prefixes. That is, don't write them yourself.
  VendorPrefix:
    enabled: true
  # Omit length units on zero values.
  ZeroUnit:
    enabled: true
