version: 0.2

phases:
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - NODE_ENV=production node ./scripts/build-styleguide-s3.js
artifacts:
  name: 'new-deploy'
  files:
    - '**/*'
  base-directory: 'dist'
