version: 0.2

phases:
  pre_build:
    commands:
      - yarn
      - GIT_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF:-$CODEBUILD_SOURCE_VERSION}
      - export GIT_BRANCH=$(echo $GIT_BRANCH | sed "s|branch/||" | sed "s|/|-|g" | sed "s|refs-heads-||")
  build:
    commands:
      - HOST=https://styleguide-dev.brainly.com VERSION=branch/$GIT_BRANCH ./scripts/build.sh -d
artifacts:
  name: '.'
  files:
    - '**/*'
  base-directory: 'dist/storybook'
